### PR TITLE
WIP: proxy: Add option to use deterministic slot IDs

### PR DESCRIPTION
**Pull request by ansasaki**
The added option makes the p11-kit-proxy module to provide slot IDs
derived from the information retrieved from the devices.  This way,
devices will get a deterministic ID regardless of the order the devices are found.

Fixes:  #266

### CODE REVIEW

**Comment by ansasaki** [comment]
@ueno Pushed with meson option and a new build in Travis. But I couldn't confirm it worked as expected (I can't see the resulting config file). Probably I should add a specific test case.

**Comment by ueno** [comment]
I'm wondering if it might make more sense to provide this option at runtime (i.e., a new configuration option in `/etc/pkcs11/pkcs11.conf`). What do you think?

**Comment by ansasaki** [comment]
> I'm wondering if it might make more sense to provide this option at runtime (i.e., a new configuration option in `/etc/pkcs11/pkcs11.conf`). What do you think?

If possible, I think it would be better. I expect the configuration to be read once and keep the same behaviour even if the configuration file option is changed during execution.

One thing that is missing in my changes is to handle collisions. Probably I'd have to change the mapping data structure to be a hashmap instead of a simple array. What do you think?

Meanwhile, I'm trying to figure out if I can also change the engine to handle situation like the one that started this whole effort: make it to detect if the handle it holds is still valid.

**Comment by ansasaki** [comment]
I found a bug which is probably the cause of the issue (#266):

When the proxy is assigning the slot IDs to the list, it reuses the IDs of slots previously found. The problem is that new slots can be found before old slots, and end up receiving the ID which were previously assigned to other slot. The resulting list would have duplicate IDs.

The solution is to first set all reused IDs and then assign the new IDs for new found slots. Other good thing to do is to make sure IDs assigned to new found slots were never used before. This is possible by making the IDs monotonically crescent.

This proposed changes (to use deterministic slots) was trying to solve the issue by the wrong approach and adding more complexity than necessary.

I will close this PR in favour of #282

**Pull request closed without merging**
