### PR TITLE
Fix CK_DATE when date is empty

### PR DESCRIPTION
**Pull request by vjardin**
Fix the issue #244 : one should return an empty buffer whenever
its length is 0.

### CODE REVIEW

**Comment by vjardin** [comment]
The travis failure is not related to this pull request. Should it work ?

**Comment by ueno** [comment]
Yes, the CI failures should be fixed with #249. Would you like to rebase against the master?

**Comment by vjardin** [comment]
Yes, I'll do it asap

**Comment by vjardin** [comment]
Hi @ueno ,
Please, can we consider this pull request despite the CI failures which are not related ? I do not have any means to fix the CI.

thank you,

**Comment by ueno** [comment]
Looks like the error on the macOS CI is actually a test failure:
```
FAIL: test-rpc 9 /rpc/byte-array-null
# assertion failed (NULL == (void*)val): (0x00000000 == 0x7f9c494028cb)
# test-rpc: assertion failed (NULL == (void*)val): (0x00000000 == 0x7f9c494028cb)
# in test_byte_array_null() at test-rpc.c:297
# test-rpc: in test_byte_array_null() at test-rpc.c:297
```
Maybe, we should somehow distinguish the cases where the value is empty or zero-length. Let me think about it a bit.

**Comment by vjardin** [comment]
Hi @ueno 

What do you think we should change in order to support both states : empty vs zero length ?  I am asking because I do not understand what's wrong.

**Comment by ueno** [comment]
Sorry @vjardin, the problem is that we also need to account for decoding the empty value. I've submitted #253 to do that.

**Comment by vjardin** [comment]
let's close this pull request, A better fix has been provided by @ueno with the pull request #253

**Pull request closed without merging**
